CREATE TABLE IF NOT EXISTS raw_frames (
  id BIGSERIAL PRIMARY KEY,
  ts_utc TIMESTAMPTZ NOT NULL,
  can_id INT NOT NULL,
  dlc SMALLINT NOT NULL,
  d1 SMALLINT, d2 SMALLINT, d3 SMALLINT, d4 SMALLINT,
  d5 SMALLINT, d6 SMALLINT, d7 SMALLINT, d8 SMALLINT,
  direction TEXT NOT NULL
);
